#!/bin/sh
DIR=`dirname $0`
if [ $# -ne 3 ]; then
    echo "$0 <server ip> <server port> <config_file>"
    exit 1
fi
while true; do
    $DIR/tcp c $1 $2 $DIR/ttun $3
    echo wait for 60 s ... >&2
    sleep 60
done

